---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demoapp
  namespace: default
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: "yhdm/complete-devops-project:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: default
spec:
  selector:
    app: yhdm/complete-devops-project
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
